#!/usr/bin/env python3
"""
Run from the repository root after slurm/run_noise_array.sh finishes.

Stitches the 120 per-task raw CSVs in results/noise/*/depolarizing_noise_raw.csv
into one run log, checks completeness, and writes:

  results/noise/noise_raw_10seed.csv         every run, one row each
  results/noise/noise_summary_10seed.csv     mean/SD per (dataset, p)
  results/noise/completeness.csv             expected vs found per dataset
  results/noise/tab_noise10.tex              the supplementary table
  results/noise/numbers_noise.tex            \\newcommand macros for the text

Nothing is rounded by hand: the .tex files are generated here, same as
build_tables.py does for the rest of the paper.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1] / "results" / "noise"
SEEDS = list(range(42, 52))
PVALS = [0.0, 0.001, 0.005, 0.010]
LABEL = {"overhead": "Overhead-MNIST", "sat6": "SAT-6", "so2sat": "So2Sat LCZ42"}
ORDER = ["overhead", "sat6", "so2sat"]


def main() -> None:
    parts = sorted(ROOT.glob("*/depolarizing_noise_raw.csv"))
    if not parts:
        sys.exit(f"no raw CSVs under {ROOT}")
    raw = pd.concat([pd.read_csv(p) for p in parts], ignore_index=True)
    raw = raw.drop_duplicates(subset=["dataset_key", "seed", "p"], keep="last")
    raw.to_csv(ROOT / "noise_raw_10seed.csv", index=False)

    # completeness
    rows = []
    for ds in ORDER:
        exp = len(SEEDS) * len(PVALS)
        found = len(raw[raw.dataset_key == ds])
        rows.append({"dataset": ds, "expected": exp, "found": found,
                     "missing": exp - found})
    comp = pd.DataFrame(rows)
    comp.to_csv(ROOT / "completeness.csv", index=False)
    print(comp.to_string(index=False))
    if comp.missing.sum():
        print("\nWARNING: incomplete. Resubmit the missing array indices before "
              "putting these numbers in the paper.")

    # one parameter count per dataset, or the checkpoints disagree
    for ds, g in raw.groupby("dataset_key"):
        n = g.total_params.nunique()
        if n != 1:
            print(f"WARNING: {ds} has {n} distinct total_params values: "
                  f"{sorted(g.total_params.unique())}. The noise rows are not "
                  f"all the same model.")

    summ = (raw.groupby(["dataset_key", "p", "gate_type", "total_params"])
               .agg(runs=("seed", "count"),
                    acc_mean=("accuracy", "mean"), acc_std=("accuracy", "std"),
                    bal_mean=("balanced_accuracy", "mean"),
                    bal_std=("balanced_accuracy", "std"),
                    f1_mean=("macro_f1", "mean"), f1_std=("macro_f1", "std"))
               .reset_index())
    summ.to_csv(ROOT / "noise_summary_10seed.csv", index=False)

    # ---- table ----
    def pm(m, s):
        return f"${100 * m:.2f} \\pm {100 * s:.2f}$"

    nseeds = int(summ.runs.max())
    lines = [
        "% generated by merge_noise.py; do not edit",
        "\\begin{table}[!t]", "\\centering", "\\footnotesize",
        "\\setlength{\\tabcolsep}{3.2pt}",
        "\\renewcommand{\\arraystretch}{1.10}",
        f"\\caption{{Robustness under a local single-rate depolarising channel: "
        f"mean test accuracy (\\%) $\\pm$ SD over {nseeds} seeds (42--51), on the "
        f"same checkpoints as Table~II.}}",
        "\\label{stab:noise}",
        "\\begin{tabular}{l c c c c c}", "\\toprule",
        "Dataset & Gate & $p=0$ & $p=0.001$ & $p=0.005$ & $p=0.010$ \\\\",
        "\\midrule",
    ]
    for ds in ORDER:
        g = summ[summ.dataset_key == ds].set_index("p")
        if g.empty:
            continue
        gate = g.iloc[0]["gate_type"]
        cells = " & ".join(pm(g.loc[p, "acc_mean"], g.loc[p, "acc_std"])
                           if p in g.index else "---" for p in PVALS)
        lines.append(f"{LABEL[ds]} & {gate} & {cells} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\\\[2pt]",
              "\\raggedright\\footnotesize The channel is applied on every qubit "
              "after the IQP encoder and after each QCNN sub-sweep. All trained "
              "parameters are held at their noiseless values, so the sweep measures "
              "inference-time robustness.",
              "\\end{table}"]
    (ROOT / "tab_noise10.tex").write_text("\n".join(lines) + "\n")

    # ---- inline macros: drop at p=0.010 relative to p=0, same checkpoints ----
    macro = ["% generated by merge_noise.py; do not edit"]
    for ds in ORDER:
        g = summ[summ.dataset_key == ds].set_index("p")
        if 0.0 in g.index and 0.010 in g.index:
            drop = 100 * (g.loc[0.0, "acc_mean"] - g.loc[0.010, "acc_mean"])
            key = {"overhead": "overhead", "sat6": "sat", "so2sat": "sosat"}[ds]
            macro.append(f"\\providecommand{{\\noisedrop{key}}}{{}}"
                         f"\\renewcommand{{\\noisedrop{key}}}{{{drop:.2f}}}")
    macro.append(f"\\providecommand{{\\noiseseeds}}{{}}"
                 f"\\renewcommand{{\\noiseseeds}}{{{nseeds}}}")
    (ROOT / "numbers_noise.tex").write_text("\n".join(macro) + "\n")

    print(f"\nwrote {ROOT}/tab_noise10.tex and numbers_noise.tex")


if __name__ == "__main__":
    main()
