#!/usr/bin/env python3
"""
Positive control: So2Sat with labels from a fixed circuit teacher (far teacher).

    python make_teacher.py teacher_far/all_runs_tqe.csv --real-runs all_runs.csv --out-dir out

Planned contrasts, fixed after the three-seed pilot and before the ten-seed run:
  primary   : trained circuit at rho_q = 1 minus frozen circuit, and minus frozen RFF
  secondary : trained circuit (rho_q = 0.1) minus frozen circuit, frozen RFF, no circuit;
              trained circuit at rho_q = 1 minus no circuit
All six are paired by seed and Holm-corrected as one family.

With --real-runs (the main-campaign log) it also writes the same rho_q = 1 contrast on the
real labels: the shared-rate runs of the schedule ablation against the frozen circuit and
frozen RFF of the isolation campaign, per dataset (uncorrected; a comparison added after the
positive control, reported as such).

Writes teacher_numbers.tex (macros for the prose) and tab_teacher.tex (supplement table).
"""
import argparse, math, os, re
import numpy as np, pandas as pd
from scipy import stats

ARMS = [("none_rhoq1", "Trained circuit, $\\rho_q=1$"), ("none", "Trained circuit, $\\rho_q=0.1$"),
        ("frozen_quantum", "Frozen circuit"), ("frozen_rff", "Frozen RFF"), ("classical_only", "No circuit")]
CONTRASTS = [("none_rhoq1", "frozen_quantum"), ("none_rhoq1", "frozen_rff"), ("none_rhoq1", "classical_only"),
             ("none", "frozen_quantum"), ("none", "frozen_rff"), ("none", "classical_only")]
SLUG = {"none_rhoq1": "rhoone", "none": "rhotenth", "frozen_quantum": "frozen", "frozen_rff": "rff",
        "classical_only": "nocirc"}


def macro(k, v):
    k = re.sub(r"[^A-Za-z]", "", k)
    return f"\\providecommand{{\\{k}}}{{}}\\renewcommand{{\\{k}}}{{{v}}}\n"


def pnum(p):
    return "$<$0.001" if p < 0.001 else f"{p:.3f}"


def ptext(p):
    return "<0.001" if p < 0.001 else f"={p:.3f}"


def holm(p):
    p = np.asarray(p, float); o = np.argsort(p); m = len(p); out = np.empty(m); run = 0.0
    for k, i in enumerate(o):
        run = max(run, (m - k) * p[i]); out[i] = min(1.0, run)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("csv"); ap.add_argument("--out-dir", default=".")
    ap.add_argument("--real-runs", default=None, help="main-campaign all_runs.csv")
    a = ap.parse_args()
    df = pd.read_csv(a.csv)
    df = df[df.config.str.contains("teacher_far")].copy()
    df["arm"] = df.config.str.extract(r"teacher_far__(.+)$")[0]
    acc = {arm: df[df.arm == arm].set_index("seed").test_acc.sort_index() for arm, _ in ARMS}
    seeds = sorted(set.intersection(*[set(s.index) for s in acc.values()]))
    n = len(seeds)
    rows = []
    for x, y in CONTRASTS:
        d = (acc[x][seeds] - acc[y][seeds]).values
        se = d.std(ddof=1) / math.sqrt(n); t = stats.t.ppf(0.975, n - 1)
        rows.append(dict(x=x, y=y, delta=d.mean(), lo=d.mean() - t * se, hi=d.mean() + t * se,
                         p=2 * stats.t.sf(abs(d.mean() / se), n - 1), npos=int((d > 0).sum())))
    R = pd.DataFrame(rows); R["p_holm"] = holm(R.p)
    lin = {c: 100 * pd.to_numeric(df[c], errors="coerce").mean()
           for c in ("teacher_lin_descriptor", "teacher_lin_angles", "teacher_lin_readout")}

    mac = ["% generated by make_teacher.py; do not edit\n", macro("teachernseeds", str(n)),
           macro("teacherlindesc", f"{lin['teacher_lin_descriptor']:.1f}"),
           macro("teacherlinangles", f"{lin['teacher_lin_angles']:.1f}"),
           macro("teacherlinreadout", f"{lin['teacher_lin_readout']:.1f}"),
           macro("teacherntests", str(len(R))),
           macro("teacherreldist", f"{pd.to_numeric(df.teacher_rel_dist, errors='coerce').mean():.2f}")]
    for arm, _ in ARMS:
        mac += [macro(f"teacheracc{SLUG[arm]}", f"{acc[arm][seeds].mean():.2f}"),
                macro(f"teachersd{SLUG[arm]}", f"{acc[arm][seeds].std(ddof=1):.2f}")]
    for _, r in R.iterrows():
        k = f"teacher{SLUG[r.x]}vs{SLUG[r.y]}"
        mac += [macro(k + "delta", f"{r.delta:+.2f}"), macro(k + "lo", f"{r.lo:+.2f}"), macro(k + "hi", f"{r.hi:+.2f}"),
                macro(k + "pt", ptext(r.p)), macro(k + "pholm", ptext(r.p_holm)), macro(k + "npos", str(r.npos))]

    real_rows = []
    if a.real_runs:
        rm, real_rows = real_rho1(a.real_runs)
        mac += rm

    lab = dict(ARMS)
    body = ["\\midrule"] + [f"{lab[arm]} & {acc[arm][seeds].mean():.2f}$\\pm${acc[arm][seeds].std(ddof=1):.2f} \\\\"
                            for arm, _ in ARMS]
    body += ["\\midrule", "\\multicolumn{2}{@{}l}{\\emph{Paired difference (pp), 95\\% CI, $p_t$, $p_{\\mathrm{Holm}}$}} \\\\"]
    for _, r in R.iterrows():
        ph = "\\textbf{" + pnum(r.p_holm) + "}" if r.p_holm < 0.05 else pnum(r.p_holm)
        body.append(f"{lab[r.x]} $-$ {lab[r.y].lower() if not lab[r.y].startswith('Frozen RFF') else 'frozen RFF'} & "
                    f"${r.delta:+.2f}$ $[{r.lo:+.2f},\\,{r.hi:+.2f}]$, {pnum(r.p)}, {ph} \\\\")
    if real_rows:
        body += ["\\midrule", "\\multicolumn{2}{@{}l}{\\emph{Real labels: trained circuit at $\\rho_q=1$ minus control (pp), 95\\% CI, $p_t$}} \\\\"]
        body += real_rows
    tab = "\\begin{tabular}{@{}lr@{}}\n\\toprule\nArm & Test accuracy (\\%) \\\\\n" + "\n".join(body) + "\n\\bottomrule\n\\end{tabular}\n"
    os.makedirs(a.out_dir, exist_ok=True)
    open(os.path.join(a.out_dir, "teacher_numbers.tex"), "w").write("".join(mac))
    open(os.path.join(a.out_dir, "tab_teacher.tex"), "w").write(tab)
    R.to_csv(os.path.join(a.out_dir, "teacher_stats.csv"), index=False)
    print(f"seeds: {seeds}")
    for arm, l in ARMS:
        print(f"  {l:32s} {acc[arm][seeds].mean():6.2f} +- {acc[arm][seeds].std(ddof=1):.2f}")
    print(R.round(4).to_string())
    print({k: round(v, 1) for k, v in lin.items()})


REAL = [("overhead_adaptive", "overhead"), ("sat6", "sat"), ("so2sat_adaptive", "sosat")]


def real_rho1(path):
    """rho_q = 1 trained circuit against the frozen controls on the real labels."""
    d = pd.read_csv(path)
    d["base"] = d.config.str.replace(r"__seed\d+$", "", regex=True)

    def acc(camp, cfg):
        s = d[(d.campaign == camp) & (d.base == cfg)].set_index("seed").test_acc.sort_index()
        assert len(s) == 10, (camp, cfg, len(s))
        return s
    out, rows = [], []
    name = {"overhead": "Overhead-MNIST", "sat": "SAT-6", "sosat": "So2Sat"}
    print("real labels, rho_q = 1 trained circuit minus control:")
    for cfg, slug in REAL:
        sh = acc("schedule", cfg + "__sharedLR")
        for ctl, cs in (("frozen_quantum", "frozen"), ("frozen_rff", "rff")):
            dd = (sh - acc("isolation", f"{cfg}__{ctl}")).values
            n = len(dd); se = dd.std(ddof=1) / math.sqrt(n); tq = stats.t.ppf(0.975, n - 1)
            p = 2 * stats.t.sf(abs(dd.mean() / se), n - 1)
            k = f"realrhoone{slug}vs{cs}"
            out += [macro(k + "delta", f"{dd.mean():+.2f}"), macro(k + "lo", f"{dd.mean() - tq * se:+.2f}"),
                    macro(k + "hi", f"{dd.mean() + tq * se:+.2f}"), macro(k + "pt", ptext(p))]
            lo, hi = dd.mean() - tq * se, dd.mean() + tq * se
            rows.append(f"{name[slug]}, {'frozen circuit' if cs == 'frozen' else 'frozen RFF'} & "
                        f"${dd.mean():+.2f}$ $[{lo:+.2f},\\,{hi:+.2f}]$, {pnum(p)} \\\\")
            print(f"  {cfg:18s} {ctl:15s} {dd.mean():+.2f} [{dd.mean()-tq*se:+.2f}, {dd.mean()+tq*se:+.2f}] p={p:.3f}")
    return out, rows


if __name__ == "__main__":
    main()
