#!/usr/bin/env python3
"""
Qubit-scaling study on So2Sat (Adaptive): trained circuit vs frozen circuit, frozen RFF,
and no circuit at every register size n_q. n_q = 10 comes from the main campaign.

    python make_scaling.py all_runs.csv scale_*/all_runs_tqe.csv --out-dir .

Writes scaling_numbers.tex (macros), tab_scaling.tex (supplement), fig_scaling.pdf/.png,
scaling_stats.csv. Delta = trained minus control (pp), paired by seed; Holm over every
test in the file; TOST at +-1 and +-0.5 pp.
"""
import argparse, math, os, re
REPRO10 = 0
import numpy as np, pandas as pd
from scipy import stats
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

ARMS = [("none", "Trained circuit", "#2a78d6", "o"), ("frozen_quantum", "Frozen circuit", "#eb6834", "s"),
        ("frozen_rff", "Frozen RFF", "#1baf7a", "D"), ("classical_only", "No circuit", "#eda100", "^")]
CTRL = ARMS[1:]
INK, MUTED, LINE, BAND = "#0b0b0b", "#52514e", "#e6e5e2", "#f3f2ef"
NUM = {8: "eight", 9: "nine", 10: "ten", 11: "eleven", 12: "twelve", 13: "thirteen", 14: "fourteen", 15: "fifteen"}


def macro(k, v):
    k = re.sub(r"[^A-Za-z]", "", k)
    return f"\\providecommand{{\\{k}}}{{}}\\renewcommand{{\\{k}}}{{{v}}}\n"


def pnum(p):
    return "$<$0.001" if p < 0.001 else f"{p:.3f}"


def ptext(p):
    return "{<}\\,0.001" if p < 0.001 else f"{{=}}\\,{p:.3f}"


def holm(p):
    p = np.asarray(p, float); o = np.argsort(p); m = len(p); out = np.empty(m); run = 0.0
    for k, i in enumerate(o):
        run = max(run, (m - k) * p[i]); out[i] = min(1.0, run)
    return out


def load(main_csv, scale_csvs):
    M = pd.read_csv(main_csv)
    rows = []
    ref = {"none": ("main", "so2sat_adaptive"), "frozen_quantum": ("isolation", "so2sat_adaptive__frozen_quantum"),
           "frozen_rff": ("isolation", "so2sat_adaptive__frozen_rff"),
           "classical_only": ("isolation", "so2sat_adaptive__classical_only")}
    for a, (camp, cfg) in ref.items():
        g = M[(M.campaign == camp) & (M.config == cfg)].copy()
        assert len(g) == 10, (cfg, len(g))
        g["ablation"], g["n_qubits"] = a, 10
        rows.append(g)
    S = pd.concat([pd.read_csv(f) for f in scale_csvs])
    S = S[S.config.str.startswith("so2sat_adaptive__nq")]
    # the scaling campaign re-trains n_q = 10; it must reproduce the main campaign exactly
    main10 = pd.concat(rows).set_index(["ablation", "seed"]).test_acc
    s10 = S[S.n_qubits == 10].set_index(["ablation", "seed"]).test_acc
    global REPRO10
    REPRO10 = len(s10)
    if len(s10):
        diff = (s10 - main10.reindex(s10.index)).abs().max()
        assert diff == 0, f"n_q=10 scaling runs differ from the main campaign by {diff}"
    S = S[S.n_qubits != 10]
    rows.append(S)
    D = pd.concat(rows)[["n_qubits", "ablation", "seed", "test_acc", "total_params", "quantum_params"]]
    D["n_qubits"] = D.n_qubits.astype(int)
    assert not D.duplicated(["n_qubits", "ablation", "seed"]).any(), "duplicate runs"
    return D


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("main_csv"); ap.add_argument("scale_csvs", nargs="+"); ap.add_argument("--out-dir", default=".")
    a = ap.parse_args()
    D = load(a.main_csv, a.scale_csvs)
    NQ = sorted(D.n_qubits.unique())
    for q in NQ:
        for arm, *_ in ARMS:
            n = len(D[(D.n_qubits == q) & (D.ablation == arm)])
            assert n == 10, f"n_q={q} {arm}: {n} runs (need 10) - rerun after the missing runs finish"
    acc = {(q, arm): D[(D.n_qubits == q) & (D.ablation == arm)].set_index("seed").test_acc for q in NQ for arm, *_ in ARMS}
    R = []
    for q in NQ:
        tr = acc[(q, "none")]
        for arm, lab, *_ in CTRL:
            c = acc[(q, arm)]; s = sorted(set(tr.index) & set(c.index)); d = (tr[s] - c[s]).values
            n = len(d); sd = d.std(ddof=1); se = sd / math.sqrt(n); t95 = stats.t.ppf(0.975, n - 1)
            r = dict(nq=q, arm=arm, label=lab, delta=d.mean(), ci_lo=d.mean() - t95 * se, ci_hi=d.mean() + t95 * se,
                     dz=d.mean() / sd, p_t=2 * stats.t.sf(abs(d.mean() / se), n - 1))
            for mg in (1.0, 0.5):
                r[f"tost{mg}"] = max(stats.t.sf((d.mean() + mg) / se, n - 1), stats.t.cdf((d.mean() - mg) / se, n - 1))
            R.append(r)
    R = pd.DataFrame(R); R["p_holm"] = holm(R.p_t)
    os.makedirs(a.out_dir, exist_ok=True)
    R.to_csv(os.path.join(a.out_dir, "scaling_stats.csv"), index=False)

    # ---------- macros
    mac = ["% generated by make_scaling.py; do not edit\n"]
    qc = R[R.arm.isin(["frozen_quantum", "frozen_rff"])]
    no = R[R.arm == "classical_only"]
    mac += [macro("scalenqmin", str(min(NQ))), macro("scalenqmax", str(max(NQ))), macro("scalennq", str(len(NQ))),
            macro("scalenqminword", NUM[min(NQ)]), macro("scalenqmaxword", NUM[max(NQ)]),
            macro("scalentests", str(len(R))), macro("scalensig", str(int((R.p_holm < 0.05).sum()))),
            macro("scalenruns", str(len(D[D.n_qubits != 10]) + REPRO10)),
            macro("scaleqpmax", str(int(D[D.n_qubits == max(NQ)].quantum_params.max()))),
            macro("scalequivone", str(int((qc["tost1.0"] < 0.05).sum()))), macro("scalequivhalf", str(int((qc["tost0.5"] < 0.05).sum()))),
            macro("scalenqc", str(len(qc))), macro("scaletostmax", f"{qc['tost1.0'].max():.3f}"),
            macro("scalefrozendeltamin", f"{R[R.arm=='frozen_quantum'].delta.min():+.2f}"),
            macro("scalefrozendeltamax", f"{R[R.arm=='frozen_quantum'].delta.max():+.2f}"),
            macro("scalerffdeltamin", f"{R[R.arm=='frozen_rff'].delta.min():+.2f}"),
            macro("scalerffdeltamax", f"{R[R.arm=='frozen_rff'].delta.max():+.2f}"),
            macro("scalenodeltamin", f"{no.delta.min():+.2f}"), macro("scalenodeltamax", f"{no.delta.max():+.2f}"),
            macro("scalenopuncmin", f"{no.p_t.min():.3f}"), macro("scalenopholmmin", f"{no.p_holm.min():.3f}"),
            macro("scalenopositive", str(int((no.delta > 0).sum()))),
            macro("scaleaccmin", f"{min(acc[(q,'none')].mean() for q in NQ):.2f}"),
            macro("scaleaccmax", f"{max(acc[(q,'none')].mean() for q in NQ):.2f}"),
            macro("scalereproten", str(REPRO10))]

    # ---------- supplement table
    rows = []
    for q in NQ:
        g = R[R.nq == q]; tr = acc[(q, "none")]
        p0 = int(D[(D.n_qubits == q) & (D.ablation == "none")].total_params.iloc[0])
        qp = int(D[(D.n_qubits == q) & (D.ablation == "none")].quantum_params.iloc[0])
        rows.append(("\\midrule\n" if q == NQ[0] else "\\addlinespace[3pt]\n")
                    + f"\\multicolumn{{7}}{{@{{}}l}}{{\\textbf{{$n_q={q}$}}: trained circuit {tr.mean():.2f}$\\pm${tr.std(ddof=1):.2f}, "
                    f"{qp} quantum of {p0} parameters{' (main campaign)' if q == 10 else ''}}} \\\\")
        for _, r in g.iterrows():
            c = acc[(q, r.arm)]
            ph = "\\textbf{" + pnum(r.p_holm) + "}" if r.p_holm < 0.05 else pnum(r.p_holm)
            e1 = "\\textbf{" + pnum(r["tost1.0"]) + "}" if r["tost1.0"] < 0.05 else pnum(r["tost1.0"])
            e5 = "\\textbf{" + pnum(r["tost0.5"]) + "}" if r["tost0.5"] < 0.05 else pnum(r["tost0.5"])
            rows.append(f"{r.label} & {c.mean():.2f}$\\pm${c.std(ddof=1):.2f} & ${r.delta:+.2f}$ & "
                        f"$[{r.ci_lo:+.2f}$ & ${r.ci_hi:+.2f}]$ & {ph} & {e1} & {e5} \\\\")
    tab = ("\\begin{tabular}{@{}llr@{\\hspace{6pt}}r@{,\;}lrrr@{}}\n\\toprule\n"
           "Control & Accuracy (\\%) & $\\Delta$ (pp) & \\multicolumn{2}{c}{95\\% CI} & $p_{\\mathrm{Holm}}$ & $p_{\\pm1}$ & $p_{\\pm0.5}$ \\\\\n"
           + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")

    # ---------- figure
    plt.rcParams.update({"font.family": "serif", "font.size": 8, "axes.labelsize": 8, "axes.edgecolor": MUTED,
                         "axes.linewidth": 0.6, "xtick.color": MUTED, "ytick.color": MUTED, "text.color": INK,
                         "axes.labelcolor": INK, "figure.facecolor": "white", "savefig.facecolor": "white"})
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(3.45, 4.1), sharex=True, gridspec_kw=dict(height_ratios=[1.15, 1], hspace=0.28))
    off = {"none": -0.18, "frozen_quantum": -0.06, "frozen_rff": 0.06, "classical_only": 0.18}
    for arm, lab, col, mk in ARMS:
        m = np.array([acc[(q, arm)].mean() for q in NQ])
        h = np.array([stats.t.ppf(0.975, 9) * acc[(q, arm)].std(ddof=1) / math.sqrt(10) for q in NQ])
        x = np.array(NQ) + off[arm]
        ax1.plot(x, m, color=col, lw=1.4, zorder=3)
        ax1.errorbar(x, m, yerr=h, fmt=mk, color=col, ms=4.5, mec="white", mew=0.6, elinewidth=1, capsize=0, zorder=4)
    ax1.set_ylabel("Test accuracy (%)")
    ax1.grid(axis="y", color=LINE, lw=0.6, zorder=0)
    ax1.set_title("(a) So2Sat, trained circuit and controls", loc="left", fontsize=8, pad=4)
    ax2.axhspan(-0.5, 0.5, color=BAND, lw=0, zorder=0)
    ax2.axhline(0, color=INK, lw=0.9, zorder=2)
    for arm, lab, col, mk in CTRL:
        g = R[R.arm == arm].sort_values("nq"); x = g.nq.values + off[arm]
        ax2.plot(x, g.delta, color=col, lw=1.4, zorder=3)
        ax2.errorbar(x, g.delta, yerr=[g.delta - g.ci_lo, g.ci_hi - g.delta], fmt=mk, color=col, ms=4.5,
                     mec="white", mew=0.6, elinewidth=1, capsize=0, zorder=4)
    ax2.set_ylabel("$\\Delta$ = trained $-$ control (pp)")
    ax2.set_xlabel("Qubits $n_q$")
    ax2.set_xticks(NQ)
    ax2.grid(axis="y", color=LINE, lw=0.6, zorder=0)
    ax2.set_title("(b) Paired difference, 95% CI; band: $\\pm0.5$ pp", loc="left", fontsize=8, pad=4)
    for ax in (ax1, ax2):
        for s in ("top", "right"):
            ax.spines[s].set_visible(False)
    hd = [Line2D([], [], color=c, marker=mk, ms=4.5, mec="white", mew=0.6, lw=1.4, label=l) for _, l, c, mk in ARMS]
    fig.legend(handles=hd, loc="lower center", ncol=2, frameon=False, fontsize=7, bbox_to_anchor=(0.55, -0.005),
               handlelength=1.8, columnspacing=1.2)
    fig.subplots_adjust(left=0.16, right=0.98, top=0.95, bottom=0.2)
    for ext in ("pdf", "png"):
        fig.savefig(os.path.join(a.out_dir, f"fig_scaling.{ext}"), dpi=300)
    open(os.path.join(a.out_dir, "tab_scaling.tex"), "w").write(tab)
    open(os.path.join(a.out_dir, "scaling_numbers.tex"), "w").write("".join(mac))
    pd.set_option("display.width", 200)
    print(R.round(3).to_string(index=False)); print("".join(mac))


if __name__ == "__main__":
    main()
