#!/usr/bin/env python3
"""
Equivalence tests (TOST) for the main controls and the no-fusion control campaign.

    python make_equivalence.py all_runs.csv all_runs_tqe.csv --out-dir .

Writes
    equiv_numbers.tex    macros for the main text (every number in the prose)
    tab_tost.tex         supplement: TOST of every quantum-branch control vs the full model
    tab_nofusion.tex     supplement: no-fusion controls vs the trained circuit without fusion

Delta is always reference minus control, in percentage points, paired by seed, as in
the main paper. TOST: two one-sided paired t-tests against +-margin; p_TOST is the larger.
"""
import argparse, math, os, re
from decimal import Decimal, ROUND_HALF_DOWN
import numpy as np, pandas as pd
from scipy import stats

DS = {"overhead": "overhead_adaptive", "sat6": "sat6", "so2sat": "so2sat_adaptive"}
DSN = {"overhead": "Overhead-MNIST", "sat6": "SAT-6", "so2sat": "So2Sat"}
SLUG = {"overhead": "overhead", "sat6": "sat", "so2sat": "sosat"}      # as in build_tables macros
MAIN_CTRL = [("classical_only", "Classical only"), ("frozen_quantum", "Frozen circuit"),
             ("frozen_rff", "Frozen RFF"), ("mlp_replace", "Trained MLP"), ("frozen_mlp", "Frozen MLP"),
             ("no_iqp", "No IQP"), ("no_reupload", "No re-upload")]
NF_CTRL = [("frozen_quantum", "Frozen circuit"), ("frozen_rff", "Frozen RFF"),
           ("mlp_replace", "Trained MLP"), ("frozen_mlp", "Frozen MLP")]
MARGINS = (1.0, 0.5)


def sg(x):
    """Signed two-decimal value; exact ties round toward zero, the convention of Tables 5 and S7."""
    d = Decimal(repr(round(float(x), 9))).quantize(Decimal("0.01"), rounding=ROUND_HALF_DOWN)
    return f"{d:+.2f}".replace("+0.00", "+0.00").replace("-0.00", "+0.00")


def macro(k, v):
    k = re.sub(r"[^A-Za-z]", "", k)
    return f"\\providecommand{{\\{k}}}{{}}\\renewcommand{{\\{k}}}{{{v}}}\n"


def pnum(p):
    return "$<$0.001" if p < 0.001 else f"{p:.3f}"


def ptext(p):             # for prose: "p<0.001" or "p=0.012"
    return "{<}\\,0.001" if p < 0.001 else f"{{=}}\\,{p:.3f}"


def holm(p):
    p = np.asarray(p, float); o = np.argsort(p); m = len(p); out = np.empty(m); run = 0.0
    for k, i in enumerate(o):
        run = max(run, (m - k) * p[i]); out[i] = min(1.0, run)
    return out


def series(df, cfg):
    s = df[df.config == cfg].set_index("seed").test_acc
    assert len(s) == 10, (cfg, len(s))
    return s


def paired(ref, ctl):
    s = sorted(set(ref.index) & set(ctl.index)); d = (ref[s] - ctl[s]).values
    n = len(d); sd = d.std(ddof=1); se = sd / math.sqrt(n)
    t95, t90 = stats.t.ppf(0.975, n - 1), stats.t.ppf(0.95, n - 1)
    r = dict(n=n, delta=d.mean(), ci_lo=d.mean() - t95 * se, ci_hi=d.mean() + t95 * se,
             ci90_lo=d.mean() - t90 * se, ci90_hi=d.mean() + t90 * se, dz=d.mean() / sd,
             p_t=2 * stats.t.sf(abs(d.mean() / se), n - 1),
             p_w=stats.wilcoxon(d).pvalue if np.any(d) else 1.0,
             ref=ref[s].mean(), ctl=ctl[s].mean(), ctl_sd=ctl[s].std(ddof=1))
    for m in MARGINS:
        r[f"tost{m}"] = max(stats.t.sf((d.mean() + m) / se, n - 1), stats.t.cdf((d.mean() - m) / se, n - 1))
    return r


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("main_csv"); ap.add_argument("tqe_csv"); ap.add_argument("--out-dir", default=".")
    a = ap.parse_args()
    M, T = pd.read_csv(a.main_csv), pd.read_csv(a.tqe_csv)
    mac = ["% generated by make_equivalence.py; do not edit\n"]

    # ---------------- 1. TOST, main controls vs full model
    rows, R1 = [], []
    for ds, cfg in DS.items():
        full = series(M[M.campaign == "main"], cfg)
        rows.append(("\\midrule\n" if ds == "overhead" else "\\addlinespace[3pt]\n")
                    + f"\\multicolumn{{6}}{{@{{}}l}}{{\\textbf{{{DSN[ds]}}} (seed SD of full model {full.std(ddof=1):.2f})}} \\\\")
        mac.append(macro(f"seedsd{SLUG[ds]}", f"{full.std(ddof=1):.2f}"))
        for c, lab in MAIN_CTRL:
            r = paired(full, series(M, f"{cfg}__{c}")); r.update(ds=ds, c=c); R1.append(r)
            e1 = "\\textbf{" + pnum(r["tost1.0"]) + "}" if r["tost1.0"] < 0.05 else pnum(r["tost1.0"])
            e05 = "\\textbf{" + pnum(r["tost0.5"]) + "}" if r["tost0.5"] < 0.05 else pnum(r["tost0.5"])
            rows.append(f"{lab} & ${sg(r['delta'])}$ & $[{sg(r['ci90_lo'])}$ & ${sg(r['ci90_hi'])}]$ & {e1} & {e05} \\\\")
    tab1 = ("\\begin{tabular}{@{}lr@{\\hspace{6pt}}r@{,\;}lrr@{}}\n\\toprule\n"
            "Control & $\\Delta$ (pp) & \\multicolumn{2}{c}{90\\% CI} & $p_{\\pm1}$ & $p_{\\pm0.5}$ \\\\\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    R1 = pd.DataFrame(R1)
    for ds in DS:
        g = R1[R1.ds == ds]
        mac.append(macro(f"tostnequiv{SLUG[ds]}", str(int((g["tost1.0"] < 0.05).sum()))))
        mac.append(macro(f"tostmax{SLUG[ds]}", ptext(g["tost1.0"].max())))
        fq = g[g.c == "frozen_quantum"].iloc[0]
        mac.append(macro(f"tostfrozen{SLUG[ds]}", ptext(fq["tost1.0"])))
        mac.append(macro(f"tosthalffrozen{SLUG[ds]}", ptext(fq["tost0.5"])))
    mac.append(macro("tostnctrl", str(len(MAIN_CTRL))))
    two = R1[R1.ds.isin(["sat6", "so2sat"])]
    mac.append(macro("tostmaxtwo", f"{two['tost1.0'].max():.3f}"))
    mac.append(macro("tosthalffrozenmaxtwo", f"{two[two.c == 'frozen_quantum']['tost0.5'].max():.3f}"))

    # ---------------- 2. no-fusion campaign vs trained circuit without fusion
    R2 = []
    for ds, cfg in DS.items():
        ref = series(M, f"{cfg}__quantum_only")
        for c, lab in NF_CTRL:
            r = paired(ref, series(T, f"{cfg}__nofusion_{c}")); r.update(ds=ds, c=c, lab=lab); R2.append(r)
    R2 = pd.DataFrame(R2); R2["p_holm"] = holm(R2.p_t)
    rows = []
    for ds, cfg in DS.items():
        g = R2[R2.ds == ds]; ref = series(M, f"{cfg}__quantum_only")
        rows.append(("\\midrule\n" if ds == "overhead" else "\\addlinespace[3pt]\n")
                    + f"\\multicolumn{{8}}{{@{{}}l}}{{\\textbf{{{DSN[ds]}}}, trained circuit {ref.mean():.2f}$\\pm${ref.std(ddof=1):.2f}}} \\\\")
        for _, r in g.iterrows():
            ph = "\\textbf{" + pnum(r.p_holm) + "}" if r.p_holm < 0.05 else pnum(r.p_holm)
            e1 = "\\textbf{" + pnum(r["tost1.0"]) + "}" if r["tost1.0"] < 0.05 else pnum(r["tost1.0"])
            rows.append(f"{r.lab} & {r.ctl:.2f}$\\pm${r.ctl_sd:.2f} & ${sg(r.delta)}$ & $[{sg(r.ci_lo)}$ & ${sg(r.ci_hi)}]$ & "
                        f"{pnum(r.p_t)} & {ph} & {e1} \\\\")
            k = f"nf{SLUG[ds]}{r.c}"
            mac += [macro(k + "delta", sg(r.delta)), macro(k + "pholm", ptext(r.p_holm)),
                    macro(k + "pt", ptext(r.p_t)), macro(k + "tost", ptext(r["tost1.0"])),
                    macro(k + "tosthalf", ptext(r["tost0.5"])), macro(k + "acc", f"{r.ctl:.2f}"),
                    macro(k + "cilo", sg(r.ci_lo)), macro(k + "cihi", sg(r.ci_hi))]
        mac += [macro(f"nf{SLUG[ds]}refacc", f"{ref.mean():.2f}"), macro(f"nf{SLUG[ds]}refsd", f"{ref.std(ddof=1):.2f}"),
                macro(f"nf{SLUG[ds]}refmin", f"{ref.min():.2f}")]
    g = R2[(R2.ds == "so2sat") & R2.c.isin(["frozen_quantum", "frozen_rff"])]
    mac.append(macro("nfsosatcircrfftostmax", ptext(g["tost1.0"].max())))
    mac += [macro("nfntests", str(len(R2))), macro("nfnsig", str(int((R2.p_holm < 0.05).sum()))),
            macro("nfnruns", str(len(T)))]
    tab2 = ("\\begin{tabular}{@{}llr@{\\hspace{6pt}}r@{,\;}lrrr@{}}\n\\toprule\n"
            "Control & Accuracy (\\%) & $\\Delta$ (pp) & \\multicolumn{2}{c}{95\\% CI} & $p_t$ & $p_{\\mathrm{Holm}}$ & $p_{\\pm1}$ \\\\\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    os.makedirs(a.out_dir, exist_ok=True)
    for f, s in (("tab_tost.tex", tab1), ("tab_nofusion.tex", tab2), ("equiv_numbers.tex", "".join(mac))):
        open(os.path.join(a.out_dir, f), "w").write(s)
    R1.to_csv(os.path.join(a.out_dir, "tost_main.csv"), index=False)
    R2.to_csv(os.path.join(a.out_dir, "nofusion_stats.csv"), index=False)
    print("".join(mac)); print(tab1); print(tab2)


if __name__ == "__main__":
    main()
