#!/usr/bin/env python3
"""
Ten-seed depolarizing-noise table (supplement) and macros, from merge_noise.py's raw log.

    python make_noise_table.py noise10/noise_raw_10seed.csv all_runs.csv --out-dir .

Checks that p = 0 reproduces the main-campaign test accuracy of the same checkpoints seed by
seed, then reports mean +- SD per rate and the seed-paired loss at the strongest rate.
"""
import argparse, math, os, re
import numpy as np, pandas as pd
from scipy import stats

ORDER = [("overhead", "Overhead-MNIST", "Adaptive", "overhead_adaptive"),
         ("sat6", "SAT-6", "Both", "sat6"),
         ("so2sat", "So2Sat LCZ42", "Shared", "so2sat_shared")]
SLUG = {"overhead": "overhead", "sat6": "sat", "so2sat": "sosat"}


def macro(k, v):
    k = re.sub(r"[^A-Za-z]", "", k)
    return f"\\providecommand{{\\{k}}}{{}}\\renewcommand{{\\{k}}}{{{v}}}\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("raw"); ap.add_argument("main_csv"); ap.add_argument("--out-dir", default=".")
    a = ap.parse_args()
    R = pd.read_csv(a.raw); M = pd.read_csv(a.main_csv)
    R["acc"] = 100 * R.accuracy
    ps = sorted(R.p.unique()); pmax = max(ps)
    mac = ["% generated by make_noise_table.py; do not edit\n"]
    rows, worst = [], 0.0
    for key, name, var, cfg in ORDER:
        g = R[R.dataset_key == key]
        assert g.groupby("p").seed.nunique().eq(10).all(), key
        ref = M[(M.campaign == "main") & (M.config == cfg)].set_index("seed").test_acc
        p0 = g[g.p == 0].set_index("seed").acc
        worst = max(worst, float((p0 - ref.reindex(p0.index)).abs().max()))
        cells = [f"${g[g.p == p].acc.mean():.2f} \\pm {g[g.p == p].acc.std(ddof=1):.2f}$" for p in ps]
        hi = g[g.p == pmax].set_index("seed").acc
        d = (p0 - hi.reindex(p0.index)).values
        se = d.std(ddof=1) / math.sqrt(len(d)); t = stats.t.ppf(0.975, len(d) - 1)
        pt = stats.ttest_rel(p0, hi.reindex(p0.index)).pvalue
        rows.append(f"{name} & {var} & {g.gate_type.iloc[0]} & " + " & ".join(cells) + f" & ${d.mean():.2f}$ \\\\")
        s = SLUG[key]
        mac += [macro(f"noisedrop{s}", f"{d.mean():.2f}"), macro(f"noisedroplo{s}", f"{d.mean() - t * se:.2f}"),
                macro(f"noisedrophi{s}", f"{d.mean() + t * se:.2f}"),
                macro(f"noisedropp{s}", "{<}\\,0.001" if pt < 0.001 else f"{{=}}\\,{pt:.3f}"),
                macro(f"noisesdhi{s}", f"{hi.std(ddof=1):.2f}"), macro(f"noisesdzero{s}", f"{p0.std(ddof=1):.2f}")]
    assert worst < 0.01, f"p = 0 does not reproduce the main campaign (max diff {worst:.3f} pp)"
    mac += [macro("noiseseeds", "10"), macro("noisepmax", f"{pmax:.3f}"),
            macro("noisereprodiff", f"{worst:.2f}")]
    head = " & ".join("$p=0$" if p == 0 else f"$p={p:.3f}$" for p in ps)
    tab = ("\\begin{tabular}{@{}lllcccc c@{}}\n\\toprule\n"
           f"Dataset & Variant & Gate & {head} & Loss \\\\\n\\midrule\n" + "\n".join(rows)
           + "\n\\bottomrule\n\\end{tabular}\n")
    tab = tab.replace("lllcccc c", "lll" + "c" * len(ps) + "c")
    os.makedirs(a.out_dir, exist_ok=True)
    open(os.path.join(a.out_dir, "tab_noise10.tex"), "w").write(tab)
    open(os.path.join(a.out_dir, "noise_numbers.tex"), "w").write("".join(mac))
    print(tab); print("".join(mac))


if __name__ == "__main__":
    main()
