#!/usr/bin/env python3
"""
Minimum detectable effect (MDE) of the seed-paired design, from the main campaign.

    python make_power.py all_runs.csv --out-dir out

For every dataset and quantum-branch control, the SD of the ten paired differences
(full model minus control) fixes the smallest true difference that a two-sided paired
t-test detects with 80% power: at alpha = 0.05, and at the strictest Holm step,
alpha = 0.05/27. Power uses the noncentral t distribution (df = 9), no approximation.

Writes power_numbers.tex (macros for the prose) and tab_power.tex (supplement table).
"""
import argparse, math, os, re
import numpy as np, pandas as pd
from scipy import stats, optimize

DS = {"overhead": "overhead_adaptive", "sat6": "sat6", "so2sat": "so2sat_adaptive"}
DSN = {"overhead": "Overhead-MNIST", "sat6": "SAT-6", "so2sat": "So2Sat"}
SLUG = {"overhead": "overhead", "sat6": "sat", "so2sat": "sosat"}
CTRL = [("classical_only", "Classical only"), ("frozen_quantum", "Frozen circuit"),
        ("frozen_rff", "Frozen RFF"), ("mlp_replace", "Trained MLP"), ("frozen_mlp", "Frozen MLP"),
        ("no_iqp", "No IQP"), ("no_reupload", "No re-upload")]
NTESTS, POWER = 27, 0.80


def macro(k, v):
    k = re.sub(r"[^A-Za-z]", "", k)
    return f"\\providecommand{{\\{k}}}{{}}\\renewcommand{{\\{k}}}{{{v}}}\n"


def series(df, cfg):
    s = df[df.config == cfg].set_index("seed").test_acc
    assert len(s) == 10, (cfg, len(s))
    return s


def power(delta, sd, n, alpha):
    """Two-sided paired t-test power for a true mean difference delta."""
    df, nc = n - 1, delta * math.sqrt(n) / sd
    tc = stats.t.ppf(1 - alpha / 2, df)
    lo = stats.nct.cdf(-tc, df, nc)                      # opposite tail; underflows to NaN far out
    return stats.nct.sf(tc, df, nc) + (0.0 if np.isnan(lo) else lo)


def mde(sd, n, alpha, target=POWER):
    return optimize.brentq(lambda d: power(d, sd, n, alpha) - target, 1e-9, 5 * sd)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("main_csv"); ap.add_argument("--out-dir", default=".")
    a = ap.parse_args()
    M = pd.read_csv(a.main_csv)
    rows, R = [], []
    for ds, cfg in DS.items():
        full = series(M[M.campaign == "main"], cfg)          # as make_equivalence.py
        for c, lab in CTRL:
            ctl = series(M, f"{cfg}__{c}")
            s = sorted(set(full.index) & set(ctl.index)); d = (full[s] - ctl[s]).values
            sd = d.std(ddof=1); n = len(d)
            R.append(dict(ds=ds, c=c, lab=lab, n=n, sd_d=sd, mde=mde(sd, n, 0.05),
                          mde_holm=mde(sd, n, 0.05 / NTESTS)))
    R = pd.DataFrame(R)

    # sanity: the solver hits the target power, and a Monte-Carlo paired t-test agrees
    rng = np.random.default_rng(0)
    for _, r in R.iterrows():
        assert abs(power(r.mde, r.sd_d, r.n, 0.05) - POWER) < 1e-6
    r0 = R.iloc[0]
    sims = rng.normal(r0.mde, r0.sd_d, size=(20000, int(r0.n)))
    p = stats.ttest_1samp(sims, 0, axis=1).pvalue
    mc = (p < 0.05).mean()
    assert abs(mc - POWER) < 0.02, mc

    mac = ["% generated by make_power.py; do not edit\n", macro("mdepower", f"{int(POWER * 100)}")]
    body = []
    for ds in DS:
        g = R[R.ds == ds]
        k = SLUG[ds]
        mac += [macro(f"mde{k}min", f"{g.mde.min():.2f}"), macro(f"mde{k}max", f"{g.mde.max():.2f}"),
                macro(f"mdeholm{k}min", f"{g.mde_holm.min():.2f}"), macro(f"mdeholm{k}max", f"{g.mde_holm.max():.2f}"),
                macro(f"mdefrozen{k}", f"{g[g.c == 'frozen_quantum'].mde.iloc[0]:.2f}")]
        body.append(("\\midrule\n" if ds == "overhead" else "\\addlinespace[3pt]\n")
                    + f"\\multicolumn{{4}}{{@{{}}l}}{{\\textbf{{{DSN[ds]}}}}} \\\\")
        for _, r in g.iterrows():
            body.append(f"{r.lab} & {r.sd_d:.2f} & {r.mde:.2f} & {r.mde_holm:.2f} \\\\")
    tab = ("\\begin{tabular}{@{}lrrr@{}}\n\\toprule\n"
           "Control & SD of $\\Delta$ (pp) & MDE, $\\alpha=0.05$ & MDE, $\\alpha=0.05/27$ \\\\\n"
           + "\n".join(body) + "\n\\bottomrule\n\\end{tabular}\n")
    os.makedirs(a.out_dir, exist_ok=True)
    open(os.path.join(a.out_dir, "power_numbers.tex"), "w").write("".join(mac))
    open(os.path.join(a.out_dir, "tab_power.tex"), "w").write(tab)
    R.to_csv(os.path.join(a.out_dir, "power.csv"), index=False)
    print(R.round(3).to_string()); print(f"Monte-Carlo power check at the first MDE: {mc:.3f}")


if __name__ == "__main__":
    main()
