#!/usr/bin/env python
"""
Three-seed hardware table and inline macros for Section V-D.

    python make_hw_seeds.py --out-dir .

Reads hw_results.json written by hw_collect.py for each seed's trained circuit
and frozen twin (same physical qubits, submitted together) and writes

    hw_seeds_numbers.tex   \\newcommand-style macros for the text
    tab_hw_seeds.tex       the tabular body of Table 7

Nothing is typed by hand. Seed 42 uses run_frozen_pinned (the frozen run on the
trained circuit's qubits), exactly as the seed-42 figure does.
"""
import argparse
import json
import os

PAIRS = [  # (seed, trained dir, frozen dir, macro letter)
    (42, "run_trained", "run_frozen_pinned", "A"),
    (43, "run_s43_trained", "run_s43_frozen", "B"),
    (44, "run_s44_trained", "run_s44_frozen", "C"),
]


def load(d):
    return json.load(open(os.path.join(d, "hw_results.json")))


def pct(x, nd=1):
    return f"{100 * x:.{nd}f}"


def span(v):
    lo, hi = min(v), max(v)
    return f"{lo}" if lo == hi else f"{lo}--{hi}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--out-dir", default=".")
    a = ap.parse_args()
    rows, macros = [], ["% generated by make_hw_seeds.py from hw_results.json; do not edit\n"]
    m = lambda k, v: macros.append(f"\\providecommand{{\\{k}}}{{}}\\renewcommand{{\\{k}}}{{{v}}}\n")
    agree, slopes, dacc = [], [], []
    for seed, td, fd, L in PAIRS:
        for kind, d in (("Trained", td), ("Frozen", fd)):
            r = load(os.path.join(a.root, d))
            assert int(r["seed"]) == seed, (d, r["seed"])
            g = r["twoq_gates_per_circuit"]
            rows.append(
                f"{seed if kind == 'Trained' else ''} & {kind} & {pct(r['acc_exact_sim'])} & "
                f"{pct(r['acc_shot_noise_mean'])}$\\pm${pct(r['acc_shot_noise_sd'])} & {pct(r['acc_hardware'])} & "
                f"{pct(r['prediction_agreement_hw_vs_sim'])} & {r['readout_shrinkage_slope']:.2f} & {span(g)} \\\\")
            agree.append(100 * r["prediction_agreement_hw_vs_sim"])
            slopes.append(r["readout_shrinkage_slope"])
            dacc.append(abs(100 * (r["acc_hardware"] - r["acc_exact_sim"])))
            m(f"hwseedslope{kind.lower()}{L}", f"{r['readout_shrinkage_slope']:.2f}")
        if seed != PAIRS[-1][0]:
            rows.append("\\addlinespace[2pt]")
    m("hwnseeds", str(len(PAIRS)))
    m("hwseedagreemin", f"{min(agree):.0f}")
    m("hwseedagreemax", f"{max(agree):.0f}")
    m("hwseedslopemin", f"{min(slopes):.2f}")
    m("hwseedslopemax", f"{max(slopes):.2f}")
    m("hwseedaccdeltamax", f"{max(dacc):.0f}")
    tab = ("\\begin{tabular}{@{}llcccccc@{}}\n\\toprule\n"
           "Seed & Circuit & Exact sim. & Shot noise & Hardware & Agreement & Slope & 2Q gates \\\\\n\\midrule\n"
           + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    os.makedirs(a.out_dir, exist_ok=True)
    open(os.path.join(a.out_dir, "tab_hw_seeds.tex"), "w").write(tab)
    open(os.path.join(a.out_dir, "hw_seeds_numbers.tex"), "w").writelines(macros)
    print("".join(macros)); print(tab)


if __name__ == "__main__":
    main()
